"""
Django settings for jango project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import environ
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
)


# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

if DEBUG:
    print("[WARNING] 😓 DEBUG FLAG IS ON!")

if not SECRET_KEY:
    print("[WARNING] 😰 Blank secret key not allowed!")
    exit(0)


ALLOWED_HOSTS = str(env('ALLOWED_HOSTS')).split(',')

CSRF_TRUSTED_ORIGINS = str(env('CSRF_TRUSTED_ORIGINS')).split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sqlitecult',
]

# Configured folder for SQLite databases
SQLITE_DATABASES_FOLDER = Path(str(env('SQLITE_DATABASES_FOLDER'))).absolute()
print(f"[*] SQLITE_DATABASES_FOLDER: {SQLITE_DATABASES_FOLDER}")
# "/home/ubuntu/n8n_data"
# SQLite Cult Settings
# Set to False to disable user registration
SQLITE_CULT_ENABLE_REGISTRATION = env('SQLITE_CULT_ENABLE_REGISTRATION')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / "staticfiles"

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'database_list'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


import os

LOG_DIRECTORY = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIRECTORY):
    os.makedirs(LOG_DIRECTORY)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # Keep Django's default loggers enabled
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{', # Use curly braces style
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler', # Output logs to the console/stderr
            'level': 'DEBUG', # Process messages of DEBUG level and higher
            'formatter': 'verbose', # Use the 'verbose' formatter
        },
        'file': {
            'class': 'logging.FileHandler', # Output logs to a file
            'filename': os.path.join(LOG_DIRECTORY, 'debug.log'), # Log file location
            'level': 'DEBUG',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': { # The "catch-all" or root logger for all app messages
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': { # The main Django logger
            'handlers': ['console', 'file'],
            'level': 'INFO', # Set Django's general log level to INFO
            'propagate': True,
        },
        'django.request': { # Logs related to handling requests (4xx/5xx responses)
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False, # Prevent propagation to parent loggers to avoid duplicate logs
        },
    }
}
