# Generated by Django 6.0 on 2025-12-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlitecult', '0003_alter_dashboardchart_chart_type_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardchart',
            name='auto_refresh',
            field=models.IntegerField(choices=[(0, 'No auto-refresh'), (30, '30 seconds'), (60, '1 minute'), (300, '5 minutes'), (600, '10 minutes'), (1800, '30 minutes'), (3600, '1 hour')], default=0, help_text='Auto-refresh interval in seconds'),
        ),
    ]
