# Generated by Django 6.0 on 2025-12-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlitecult', '0005_databaseownership_databasepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseownership',
            name='api_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseownership',
            name='api_secret_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
