# Generated by Django 6.0 on 2025-12-29 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlitecult', '0006_databaseownership_api_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='databasepermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='databasepermission',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='databasepermission',
            name='granted_to',
        ),
        migrations.CreateModel(
            name='SqliteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(editable=False, help_text='Internal unique filename for the SQLite file', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Display name for the database', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_enabled', models.BooleanField(default=False)),
                ('api_token', models.TextField(blank=True, help_text='JWT token for API access', null=True)),
                ('api_permissions', models.JSONField(blank=True, default=list, help_text='List of permissions for API: read, create, update, delete')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_sqlite_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SQLite File',
                'verbose_name_plural': 'SQLite Files',
                'ordering': ['-created_at'],
                'permissions': (('view_database', 'Can view SQLite database'), ('add_data', 'Can add data to tables'), ('change_data', 'Can modify data in tables'), ('delete_data', 'Can delete data from tables')),
            },
        ),
        migrations.DeleteModel(
            name='DatabaseOwnership',
        ),
        migrations.DeleteModel(
            name='DatabasePermission',
        ),
    ]
