# Generated by Django 6.0 on 2025-12-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlitecult', '0007_alter_databasepermission_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for the table')),
                ('description', models.TextField(blank=True, null=True)),
                ('sqlite_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_metadata', to='sqlitecult.sqlitefile')),
            ],
            options={
                'verbose_name': 'Table Metadata',
                'verbose_name_plural': 'Table Metadata',
                'unique_together': {('sqlite_file', 'table_name')},
            },
        ),
    ]
