# Generated by Django 6.0 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlitecult', '0008_tablemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardchart',
            name='chart_width',
            field=models.PositiveSmallIntegerField(
                choices=[(4, 'Small (1/3 width)'), (6, 'Medium (1/2 width)'), (8, 'Wide (2/3 width)'), (12, 'Full width')],
                default=6,
                help_text='Width of the chart card in the dashboard grid',
            ),
        ),
    ]