# Generated by Django 6.0 on 2026-03-11 00:00

from django.db import migrations, models


def convert_chart_width_to_pixels(apps, schema_editor):
    DashboardChart = apps.get_model('sqlitecult', 'DashboardChart')
    width_mapping = {
        4: 420,
        6: 640,
        8: 860,
        12: 1080,
    }

    for chart in DashboardChart.objects.all():
        chart.chart_width = width_mapping.get(chart.chart_width, 640)
        chart.save(update_fields=['chart_width'])


class Migration(migrations.Migration):

    dependencies = [
        ('sqlitecult', '0009_dashboardchart_chart_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardchart',
            name='chart_width',
            field=models.PositiveIntegerField(default=640, help_text='Width of the chart card in pixels'),
        ),
        migrations.RunPython(convert_chart_width_to_pixels, migrations.RunPython.noop),
        migrations.AddField(
            model_name='dashboardchart',
            name='chart_height',
            field=models.PositiveIntegerField(default=360, help_text='Height of the chart card in pixels'),
        ),
    ]